# Generated by Django 4.0.3 on 2022-03-16 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiclemanagement', '0002_alter_vehicle_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='numberPlate',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
