# Generated by Django 4.0.3 on 2022-03-16 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiclemanagement', '0003_vehicle_numberplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='numberPlate',
            field=models.CharField(default='kaa', max_length=255),
            preserve_default=False,
        ),
    ]
