# Generated by Django 4.0.3 on 2022-04-25 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehiclemanagement', '0007_alter_user_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='vehiclemanagement.user'),
        ),
    ]
