# Generated by Django 4.0.3 on 2022-04-26 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiclemanagement', '0010_alter_user_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='owner',
            field=models.CharField(max_length=30),
        ),
    ]
