# Generated by Django 4.0.3 on 2022-04-26 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiclemanagement', '0011_alter_vehicle_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='owner',
        ),
    ]
