# Generated by Django 4.0.3 on 2022-05-07 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehiclemanagement', '0012_remove_vehicle_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='vehiclemanagement.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='phoneNumber',
            field=models.PositiveIntegerField(default='+254712345678'),
        ),
    ]
