# Generated by Django 3.2 on 2022-05-07 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiclemanagement', '0013_vehicle_owner_alter_user_phonenumber'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-phone_number'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelOptions(
            name='vehicle',
            options={'ordering': ['-yom'], 'verbose_name': 'Vehicle', 'verbose_name_plural': 'Vehicles'},
        ),
        migrations.RenameField(
            model_name='user',
            old_name='dateOfBirth',
            new_name='dob',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='phoneNumber',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='numberPlate',
            new_name='number_plate',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='updatedAt',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='yearofmanufacture',
            new_name='yom',
        ),
    ]
